[tasks.lint]
run = "cargo clippy --all-targets --all-features"

[tasks.release]
run = "cargo build --release"

[tasks.build]
run = "cargo build"

[tasks.cli]
run = "cargo run -- -f releasor"

[tasks.test]
run = "cargo test"

[tasks.check]
run = "cargo check"

[tasks.doc]
run = "cargo doc --no-deps"

[tasks.fmt]
run = "cargo fmt --all -- --check"

[tasks.changelog]
run = "git cliff -o CHANGELOG.md"

